# ${license-info}
# ${developer-info}
# ${author-info}


=head1 NAME

diskless_server: NCM component to configure a server for diskless clients

=head1 DESCRIPTION

the I<diskless_server> component configures a server for diskless clients
using the pxeos and pxeboot commands to create the pxe boot files.
It also configures the dhcpd using the aii quattor component.NFS and tftp are
not configured by this component.


=head1 RESOURCES

=head2 /software/components/diskless_server/dhcp_header

Global dhcp options.

=head3 /software/components/diskless_server/dhcp_header/ddns_update_style

Possible values : ad-hoc, interim, none

=head3 /software/components/diskless_server/dhcp_header/unknown_clients

Possible values : allow or deny

=head3 /software/components/diskless_server/dhcp_header/use_host_decl_names

Possible values : on or off

=head3 /software/components/diskless_server/dhcp_header/log_facility

Sets the logging facility used by dhcpd

=head3 /software/components/diskless_server/dhcp_header/search

Sets the domains that will be searched (for resolv.conf)

=head2 /software/components/diskless_server/dhcp/_xxx.xxx.xxx.xxx/

list that contains the options for each dhcp subnet
the name of the subnet must be of the form _xxx.xxx.xxx.xxx

=head3 /software/components/diskless_server/dhcp/_xxx.xxx.xxx.xxx/subnet : type_hostname

=head3 /software/components/diskless_server/dhcp/_xxx.xxx.xxx.xxx/netmask : type_hostname

define the netmask and subnet name

=head3 /software/components/diskless_server/dhcp/_xxx.xxx.xxx.xxx/options

nlist with specific dhcp options for each subnet.
Supported now are: routers,domain-name-servers,time-servers

=head2 /software/components/diskless_server/nodes : type_hostname list

List of diskless nodes that will boot from this server

=head2 /software/components/diskless_server/pxe/

named list with options to create the pxe boot files

=head3 /software/components/diskless_server/pxe/descro : string

Description of the OS

=head3 /software/components/diskless_server/pxe/protocol : string

Protocol to access the operating system.NFS,FTP,HTTP
NFS is the only possible option,to be removed

=head3 /software/components/diskless_server/pxe/kernel : string

Kernel to be used(Might not be needed)

=head3 /software/components/diskless_server/pxe/image : string

The location of the OS files

=head3 /software/components/diskless_server/pxe/name : string

The name of the OS

=head3 /software/components/diskless_server/pxe/ramdisk : long

Size of the ramdisk,if not set default is 40MB

=head3 /software/components/diskless_server/pxe/netdev: string

The name of the active network device (eth0,wlan0,etc...)

=head2 /software/components/diskless_server/rwfiles : strings list

List containing the files to be added in files.custom

=head2 /software/components/diskless_server/aii

Information about the cdb location and the profiles

=head3 /software/components/diskless_server/aii/cdb : string

The exact location of the profiles(URL)

=head3 /software/components/diskless_server/aii/prefix : string

The prefix for the profile nodes(usually profile_)

Since we are using AII it's pod should be read on how to add dhcp entries.
here is an example that must be in the client's profile.IPs used are the client's
"/software/components/aii/dhcp/options/tftpserver" = "pcitadc35";
"/software/components/aii/dhcp/options/addoptions" = "filename \"linux-install/pxelinux.0\"; option root-path \"137.138.8.155:/diskless/i386/slc3/root/\";";
"/software/components/aii/active" = false;   # aii is no real component, thus
"/software/components/aii/dispatch" = false; # it is not active

=cut
