# ${license-info}
# ${developer-info}
# ${author-info}


=head1 NAME

NCM::Component::spma - Quattor's package manager

=head1 SYNOPSIS

The SPMA component passes off to different back-ends depending
on the type of packaging system specified in
B</software/components/spma/packager>. Optionally there can be
invoked a different module than default one for a single
packaging system once B</software/components/spma/suffix> with
suffix name is defined.

See B<NCM::Component::spma::yum> for Yum (also 
B<NCM::Component::spma::yumng optional module for Yum) and
B<NCM::Component::spma::ips> for Solaris IPS.

=cut
