# ${license-info}
# ${developer-info}
# ${author-info}

=head1 NAME

NCM::Component::spma - Quattor's package manager

=head1 SYNOPSIS

The SPMA component passes off to different back-ends depending
on the type of packaging system specified in
C<< /software/components/spma/packager >>.

Currently available:

=over

=item * C<< NCM::Component::spma::ips >> for Solaris.

=item * C<< NCM::Component::spma::yum >>

=item * C<< NCM::Component::spma::yumng >>

=back

=cut
