# ${license-info}
# ${developer-info}
# ${author-info}


=begin comment

Be sure to put a blank line before and after every formatting command

=end comment

=head1 NAME

directoryservices : Directory Services NCM component.

=head1 DESCRIPTION

Component to manage directory services on OS X. This can both setup local directory (e.g. for MCX purposes) and provide linkage to external open directory services. When defining a network open directory server, the configuration is at the moment pretty "raw" - interpreted and passed "as-is" to OS X.

=head1 RESOURCES

=head2 /software/components/directoryservices/...

=head1 DEPENDENCIES

None.

=head1 BUGS

None known.

=head1 AUTHOR

Nick Williams <Nick.Williams@morganstanley.com>

=head1 MAINTAINER

Nick Williams <Nick.Williams@morganstanley.com>

=head1 VERSION

1.0.0

=head1 SEE ALSO

ncm-ncd(1)

=cut
