# ${license-info}
# ${developer-info}
# ${author-info}

# Coding style: emulate <TAB> characters with 4 spaces, thanks!
################################################################################

=head1 NAME

NCM::runlevel - NCM runlevel configuration component

=head1 SYNOPSIS

=item Configure()

Replaces the initdefault runlevel by what is configured in CDB if configured there.

=item Unconfigure()

Do nothing

=head1 RESOURCES

=item /software/components/runlevel/active: boolean

activates/deactivates the component.

=item /software/components/runlevel/initdefault : integer in (1,2,3,4,5)

Define the runlevel used for initdefault

=head1 DEPENDENCIES

none

=head2 Components to be run before:

none.

=head2 Components to be run after:

none.

=head1 BUGS

none known.

=head1 AUTHOR

Veronique Lefebure <Veronique.Lefebure@cern.ch>

=head1 SEE ALSO

ncm-ncd(1)

=cut


