# ${license-info}
# ${developer-info}
# ${author-info}


=pod

=head1 DESCRIPTION

This component configures amanda server, the  "Advanced  Maryland  Automatic  
Network  Disk  Archiver"

=head1 FILES

This component touches the following files: 
/etc/amanda/backupname/amanda.conf
/etc/amanda/backupname/disklist 

=head1 STRUCTURE

These are the top-level fields provided by the component. For
information on any of these fields' structure, please look amanda's
documentation. 

=over 6

=item * /software/components/amandaserver/backupname/config/general_options

Named list of general configuration options.

=item * /software/components/amandaserver/backupname/config/holdingdisks : holdingdisk{}

Named list of C<holdingdisk> structures, indexed by C<holdingdisk>
name.

=item * /software/components/amandaserver/backupname/config/tapetypes : tapetype{}

Named list of C<tapetype> structures, indexed by C<tapetype> name. 

=item * /software/components/amandaserver/backupname/config/dumptypes : dumptype{}

Named list of C<dumptype> structures, indexed by C<dumptype> name.

=item * /software/components/amandaserver/backupname/config/interfaces : interface{}

Named list of C<interface> structures, indexed by C<interface> name.

=item * /software/components/amandaserver/backupname/disklists : disk[]

List of C<disk> structures

=back

=cut
