# ${license-info}
# ${developer-info}
# ${author-info}


=pod

=head1 DESCRIPTION

This component configures amanda server, the "Advanced Maryland Automatic
Network Disk Archiver".

=head1 FILES

This component generates the following files:

=over

=item * C<< /etc/amanda/backupname/amanda.conf >>

=item * C<< /etc/amanda/backupname/disklist >>

=back

Furthermore, when using virtual tapes (C<< tpchanger='chg-disk' >>) it creates
(only if these files do not exist previously):

=over

=item * C<< /etc/amanda/backupname/tapelist >>

=item * C<< tapedev_dir/slotXX >>

=item * symbolic to the first slot

=back

It also labels the virtual tapes (this is very dangerous cause labelling
the tapes destroy the content, have this into account if you already
have data in the tapedev directory)

=head1 STRUCTURE

These are the top-level fields provided by the component. For
information on any of these fields' structure, please look amanda's
documentation.

=over 6

=item * C<< /software/components/amandaserver/backupname/config/general_options >>

Named list of general configuration options (goes to C<< /etc/amanda/backupname/amanda.conf >>).
Depending on the value of option C<< tpchanger >> it might create the virtual tapes in the path
specified by option C<< tapedev >>.

=item * C<< /software/components/amandaserver/backupname/config/holdingdisks : holdingdisk{} >>

Named list of C<holdingdisk> structures, indexed by C<holdingdisk>.
name (goes to /etc/amanda/backupname/amanda.conf).

=item * C<< /software/components/amandaserver/backupname/config/tapetypes : tapetype{} >>

Named list of C<tapetype> structures, indexed by C<tapetype> name.
(goes to /etc/amanda/backupname/amanda.conf).

=item * C<< /software/components/amandaserver/backupname/config/dumptypes : dumptype{} >>

Named list of C<dumptype> structures, indexed by C<dumptype> name.
(goes to /etc/amanda/backupname/amanda.conf).

=item * C<< /software/components/amandaserver/backupname/config/interfaces : interface{} >>

Named list of C<interface> structures, indexed by C<interface> name.
(goes to /etc/amanda/backupname/amanda.conf).

=item * C<< /software/components/amandaserver/backupname/disklists : disk[] >>

List of C<disk> structures (goes to /etc/amanda/backupname/disklist).

=back

=cut
