# ${license-info}
# ${developer-info}
# ${author-info}
# ${build-info}

=head1 NAME

ncm-${project.artifactId}: Configuration module for CEPH

=head1 DESCRIPTION

Main module that compares the configuration inside 
the templates with those on the machines and build structures 
that the daemon and config module can handle to perform action

=head1 AUTHOR

${author-info}

=cut
