# ${license-info}
# ${developer-info}
# ${author-info}


=head1 NAME

NCM::shorewall - NCM shorewall configuration component

=head1 SYNOPSIS

=over

=item Configure()

This component configures Shorewall.

=item  /software/components/shorewall/rules

=item  /software/components/shorewall/interfaces

=item  /software/components/shorewall/zones


=back

=head1 DEPENDENCIES

=head2 Components to be run before:

none.

=head2 Components to be run after:

none.

=head1 BUGS

none known.

=head1 AUTHOR

Stijn De Weirdt <stijn.dweirdt@ugent.be>

=head1 SEE ALSO

ncm-ncd(1), shorewall(1)

=cut
