# ${license-info}
# ${developer-info}
# ${author-info}

=head1 NAME

NCM::shorewall - NCM shorewall configuration component

=head1 SYNOPSIS

=over

=item Configure()

This component configures Shorewall.

=over

=item * /software/components/shorewall/rules

=item * /software/components/shorewall/interfaces

=item * /software/components/shorewall/zones

=back

=back

=cut
