# ${license-info}
# ${developer-info}
# ${author-info}


=head1 NAME

The I<cdp> component manages the configuration file
C<< /etc/cdp-listend.conf. >>

=head1 DESCRIPTION

The I<cdp> component manages the configuration file for the
cdp-listend daemon.

=head1 RESOURCES

=over

=item * C<< configfile : string >>

The location of the configuration file.  Normally this should not be
changed.  Defaults to C<< /etc/cdp-listend.conf >>

=item * C<< port ? type_port >>

The port used by the daemon.  

=item * C<< nch ? string >>

The binary to execute when receiving a CDB update packet.

=item * C<< nch_smear ? long(0..) >>

The range of time delay for executing the nch executable.  The
execution will be delayed by [0, nch_smear] seconds.

=item * C<< fetch ? string >>

The binary to execute when receiving a CCM update packet.

=item * C<< fetch_smear ? long(0..) >>

The range of time delay for executing the fetch executable.  The
execution will be delayed by [0, fetch_smear] seconds.

=back

=head1 EXAMPLES

  "/software/components/cdp/fetch" = "/usr/sbin/ccm-fetch";
  "/software/components/cdp/fetch_smear" = 30;

=cut
