# ${license-info}
# ${developer-info}
# ${author-info}



=head1 NAME

NCM::pine - pine/alpine email client configuration component

=head1 SYNOPSIS

=over 2

=item Configure()

Configures systemwide C</etc/pine.conf> and
C</etc/apline/pine.conf>. Missing files/directories will be
created. Both files have he same content (for now).

=item Unconfigure()

resets everything to default (empty values)

=back

=head1 RESOURCES

=over 2

=item /software/components/pine/active : boolean

activates/deactivates the component.

=item /software/components/pine/userdomain : string

=item /software/components/pine/smtpserver : string

=item /software/components/pine/nntpserver : string

=item /software/components/pine/inboxpath : string

=item /software/components/pine/foldercollection : string

=item /software/components/pine/ldapservers : string,

LDAP server and search string

=item /software/components/pine/ldapnameattr : string,

 which LDAP attribute gets mapped to "name"

=item /software/components/pine/disableauth : string,

authentication methods to disable (in case they are not sufficiently
supported by the mail server,e.g "GSSAPI")

=back

=head1 DEPENDENCIES

=head2 Components to be run before:

none.

=head2 Components to be run after:

none.

=head1 AUTHOR

Jaroslaw Polok <jaroslaw.polok@cern.ch>

=head1 SEE ALSO

pine.conf(5), lcm(8) or ncm-ncd(8)

=cut


### Local Variables: ///
### mode: perl ///
### End: ///
