# ${license-info}
# ${developer-info}
# ${author-info}
# ${build-info}

=head1 NAME

ncm-postfix: Postfix server configuration

=head1 DESCRIPTION

postfix

=head1 RESOURCES

=head2 /software/components/postfix

The configuration information for the component.  Each field should
be described in this section. 

=head1 AUTHOR

${author-info}

=cut
