# ${license-info}
# ${developer-info}
# ${author-info}


=head1 NAME

sysconfig: management of sysconfig files

=head1 DESCRIPTION

The I<sysconfig> component manages system configuration files in
C<< /etc/sysconfig >> . These are files which contain key-value pairs.
However there is the possibility to add verbatim text either
before or after the key-value pair definitions.

=head1 FILE DEFINITIONS

=over

=item * C<< /software/components/sysconfig/files >>

This is an nlist which has the file name (unescaped) as the key, and
the content information as the value. The value is an nlist.

=item * C<< /software/components/sysconfig/files/<fname>/ >>

This is a nlist containing key-value pairs. Both are strings.
There are two special keys C<< prologue >> and C<< epilogue >> which contain
text which will be copied verbatim into the file before or after
the pair definitions, respectively.

=back

=head1 EXAMPLE

  "/software/components/sysconfig/files/scfg" =
    nlist("epilogue", "export LANG=C",
        "KEY", "VALUE");

This will create the file C<< /etc/sysconfig/scfg >> which contains:

  KEY=VALUE
  export LANG=C

=cut
