# ${license-info}
# ${developer-info}
# ${author-info}


=head1 NAME

NCM::ofed - NCM ofed configuration component

=head1 SYNOPSIS

=over

=item Configure()

This component configures OFED.

=item  C<< /software/components/ofed/openib >>

=item config 

Config file loaction for openib (default C<< /etc/infiniband/openib.conf >>).

=item options

Config options

=item modules

Modules to load

=item hardware

Hardware modules to load

=back

=cut
