# ${license-info}
# ${developer-info}
# ${author-info}

=head1 NAME

NCM::ssh - NCM SSH configuration component

=head1 DESCRIPTION

Update the SSH client and/or daemon configuration files, preserving their
permissions. Replace changed option values and add new options to the end of the
configuration file(s).

If any changes were made in the daemon configuration file, tell the SSH daemon to
reload the new configuration by executing the following command:

  /sbin/service sshd reload

=head1 RESOURCES

=over

=item * C<< /software/components/ssh/client >> : nlist (optional)

This nlist contains 2 option sets describing respectively options that must be defined
an their values and options that must be commented out.

=over

=item * C<< /software/components/ssh/client/options >> : nlist (optional)

Options that must be set and their value. See schema for allowed options.

=item * C<< /software/components/ssh/client/comment_options >> : nlist (optional)

Options that must be commented out. This is the same set of options as those which can be
set. If an option is in both list, definition takes precedence.

See schema for allowed options.

=back

=item * C<< /software/components/ssh/daemon >> : nlist (optional)

This nlist contains 2 option sets describing respectively options that must be defined
an their values and options that must be commented out.

=over

=item * C<< /software/components/ssh/daemon/options >> : nlist (optional)

Options that must be set and their value. See schema for allowed options.

=item * C<< /software/components/ssh/daemon/comment_options >> : nlist (optional)

Options that must be commented out. This is the same set of options as those which can be
set. If an option is in both list, definition takes precedence.

See schema for allowed options.

=back

=back

=head1 FILES

=over

=item C<< /etc/ssh/sshd_config >>

The SSH daemon configuration file.

=item C<< /etc/ssh/ssh_config >>

The SSH client configuration file.

=back

=cut
