use strict;
use warnings;

BEGIN {
    *CORE::GLOBAL::sleep = sub {};
}

use Test::More;
use Test::Quattor qw(nmstate_simple);
use Test::MockModule;
use Readonly;

use NCM::Component::nmstate;
my $mock = Test::MockModule->new('NCM::Component::nmstate');
my %executables;
$mock->mock('_is_executable', sub {diag "executables $_[1] ",explain \%executables;return $executables{$_[1]};});

my $cfg = get_config_for_profile('nmstate_simple');
my $cmp = NCM::Component::nmstate->new('network');

Readonly my $NETWORK => 'x' x 100;

Readonly my $RESOLV => <<EOF;
managed by something else
EOF

Readonly my $NODNS => <<EOF;
[main]
dns=none
EOF

Readonly my $ETH0_YML => <<EOF;
# File generated by NCM::Component::nmstate. Do not edit
---
interfaces:
- link-aggregation:
    port: []
  name: eth0
  type: bond
EOF

# TODO: there should e no reason for this. we can assume it's there in EL9
$executables{'/usr/bin/hostnamectl'} = 1;

set_file_contents("/etc/resolv.conf", "$RESOLV");

set_file_contents("/etc/nmstate/toremove.yml", "something");


command_history_reset();
is($cmp->Configure($cfg), 1, "Component runs correctly with a test profile");

my $fh;

# resolv.conf is unchanged
is(get_file_contents("/etc/resolv.conf"), $RESOLV, "Exact network config");

# set nm config to disable dns mgmt
is(get_file_contents("/etc/NetworkManager/conf.d/90-quattor-dns-none.conf"), $NODNS, "disable NM dns mgmt");

# unconfigure nmstate yml is removed
ok(!$cmp->file_exists("/etc/nmstate/toremove.yml"), "unconfigured yml nmstate is removed");

my $eth0yml = get_file_contents("/etc/nmstate/eth0.yml");
is($eth0yml, $ETH0_YML, "Exact eth0 yml config");

diag "all history commands ", explain \@Test::Quattor::command_history;
ok(command_history_ok([
  'ls -ltr /etc/nmstate',
  'ip addr show',
  'ip route show',
  '/usr/bin/nmstatectl show',
  '/usr/bin/nmcli dev status',
  '/usr/bin/nmcli connection',
  'ip addr show',
  'systemctl enable NetworkManager',
  '/usr/bin/hostnamectl set-hostname somehost.test.domain --static',
  'ls -ltr /etc/nmstate',
  'ip addr show',
  'ip route show',
  '/usr/bin/nmstatectl show',
  '/usr/bin/nmcli dev status',
  '/usr/bin/nmcli connection',
  'service NetworkManager reload',
  'systemctl disable nmstate',
  '/usr/bin/nmcli -t -f name conn',
  '/usr/bin/nmstatectl apply /etc/nmstate/eth0.yml',
  '/usr/bin/nmstatectl apply /etc/nmstate/resolv.yml',
  'service NetworkManager reload',
  'ls -ltr /etc/nmstate',
  'ip addr show',
  'ip route show',
  '/usr/bin/nmstatectl show',
  '/usr/bin/nmcli dev status',
  '/usr/bin/nmcli connection',
  'ccm-fetch'
], []));

command_history_reset();

done_testing();
