use strict;
use warnings;

BEGIN {
    *CORE::GLOBAL::sleep = sub {};
}

use Test::More;
use Test::Quattor qw(nmstate_bridge);
use Readonly;

use NCM::Component::nmstate;

my $cfg = get_config_for_profile('nmstate_bridge');
my $cmp = NCM::Component::nmstate->new('network');

Readonly my $BR0_YML => <<EOF;
# File generated by NCM::Component::nmstate. Do not edit
---
interfaces:
- bridge:
    options:
      stp:
        enabled: true
        forward-delay: 5
    port:
    - name: eth0
  ipv4:
    address:
    - ip: 4.3.2.1
      prefix-length: 24
    dhcp: false
    enabled: true
  name: br0
  profile-name: br0
  state: up
  type: linux-bridge
routes:
  config:
  - next-hop-interface: br0
    state: absent
  - destination: 0.0.0.0/0
    next-hop-address: 4.3.2.254
    next-hop-interface: br0
EOF

Readonly my $ETH0_YML => <<EOF;
# File generated by NCM::Component::nmstate. Do not edit
---
interfaces:
- ipv4:
    enabled: false
  ipv6:
    enabled: false
  mac-address: 6e:a5:1b:55:77:0a
  name: eth0
  profile-name: eth0
  state: up
  type: ethernet
EOF

is($cmp->Configure($cfg), 1, "Component runs correctly with a Linux bridge profile");

my $br0yml = get_file_contents("/etc/nmstate/br0.yml");
is($br0yml, $BR0_YML, "Exact br0 linux-bridge yml config");

my $eth0yml = get_file_contents("/etc/nmstate/eth0.yml");
is($eth0yml, $ETH0_YML, "Exact bridge-port eth0 yml config");

done_testing();