use strict;
use warnings;

BEGIN {
    *CORE::GLOBAL::sleep = sub {};
}

use Test::More;
use Test::Quattor qw(nmstate_simple);
use Test::MockModule;
use Readonly;

use NCM::Component::nmstate;
my $mock = Test::MockModule->new('NCM::Component::nmstate');
my %executables;
$mock->mock('_is_executable', sub {diag "executables $_[1] ",explain \%executables;return $executables{$_[1]};});

my $cfg = get_config_for_profile('nmstate_simple');
my $cmp = NCM::Component::nmstate->new('network');

Readonly my $NETWORK => <<EOF;
NETWORKING=yes
GATEWAY=4.3.2.254
EOF

Readonly my $RESOLV => <<EOF;
managed by something else
EOF

Readonly my $NODNS => <<EOF;
[main]
dns=none
EOF

Readonly my $ETH0_YML => <<EOF;
# File generated by NCM::Component::nmstate. Do not edit
---
device: eth0
link_aggregation:
  port: []
name: eth0
type: bond
EOF

# TODO: there should e no reason for this. we can assume it's there in EL9
$executables{'/usr/bin/hostnamectl'} = 1;

# TODO: why is this still used? can we get rid of doing anything with it?
set_file_contents("/etc/sysconfig/network", 'x' x 100);

set_file_contents("/etc/resolv.conf", "$RESOLV");

set_file_contents("/etc/nmstate/toremove.yml", "something");


command_history_reset();
is($cmp->Configure($cfg), 1, "Component runs correctly with a test profile");

my $fh;

$fh = get_file($cmp->testcfg_filename("/etc/sysconfig/network"));
ok(! defined($fh), "testcfg network file was cleaned up");

# on success, this is hardlink of a cleaned up testcfg; can't use get_file
is(get_file_contents("/etc/sysconfig/network"), $NETWORK, "Exact network config");

# resolv.conf is unchanged
is(get_file_contents("/etc/resolv.conf"), $RESOLV, "Exact network config");

# set nm config to disable dns mgmt
is(get_file_contents("/etc/NetworkManager/conf.d/90-quattor-dns-none.conf"), $NODNS, "disable NM dns mgmt");

# unconfigure nmstate yml is removed
ok(!$cmp->file_exists("/etc/nmstate/toremove.yml"), "unconfigured yml nmstate is removed");
my $eth0yml = get_file_contents("/etc/nmstate/eth0.yml");
is($eth0yml, $ETH0_YML, "Exact eth0 yml config");


ok(command_history_ok([], []));

done_testing();
