# ${license-info}
# ${developer-info}
# ${author-info}


=head1 NAME

NCM::oramon-server - NCM Oramon server configuration component

=head1 SYNOPSIS

Component for configuring the oramon-server.

=over

=item Configure()

Writes the /etc//oramon-server.conf file that stores the data for metric
classes' and their instances' table structure.

=back

=head1 DEPENDENCIES

None.

=head1 BUGS

None known.

=head1 AUTHOR

Teemu Sidoroff <Teemu.Sidoroff@cern.ch>

=head1 SEE ALSO

ncm-ncd(1)

=cut
