################################################################################
# This is 'openldap.pod', a ncm-openldap's file
################################################################################
#
# VERSION:    1.0.0-3, 02/02/10 15:50
# AUTHOR:     Daniel Jouvenot <jouvenot@lal.in2p3.fr>
# MAINTAINER: Guillaume Philippon <philippo@lal.in2p3.fr>
# LICENSE:    http://cern.ch/eu-datagrid/license.html
#
################################################################################
# Coding style: emulate <TAB> characters with 4 spaces, thanks!
################################################################################

=head1 NAME

openldap -- NCM component to control entries in /etc/openldap/slapd.conf

=head1 DESCRIPTION

The I<openldap> component manages the opeldap server config file /etc/openldap/slapd.conf.