# ${license-info}
# ${developer-info}
# ${author-info}


=head1 NAME

NCM::pacemaker - NCM pacemaker for Linux-HA configuration component

=head1 SYNOPSIS

=over

=item Configure()

Creates (overwrites!) the following files based on CDB information:

F</etc/ha.d/ha.cf>

F</etc/ha.d/authkeys>

Resources are managed through pacemaker CRM.

Method also tells Linux-HA daemon (heartbeat) to reload the new configuration
by calling this command:

service heartbeat reload

=item Unconfigure()

Does nothing.

=back

=head1 EXAMPLES

See README file or check QWG repository.

=head1 RESOURCES

=over

=item /software/components/pacemaker/active : boolean

activates/deactivates the component.

=back

=head1 DEPENDENCIES

None.

=head1 BUGS

None known.

=head1 AUTHOR

Stijn De Weirdt <stijn.deweirdt@ugent.be>

=head1 SEE ALSO

ncm-ncd(1), /usr/share/doc/heartbeat/

=cut
