# ${license-info}
# ${developer-info}
# ${author-info}


=pod

=head1 DESCRIPTION

This component configures the nagios addon, pnp4nagios

=head1 FILES

This component touches the following files: 
/etc/pnp4nagios/npcd.cfg
/etc/pnp4nagios/config.php

and creates pages and/or templates in the specified directories

=head1 STRUCTURE

These are the top-level fields provided by the component. For
information on any of these fields' structure, please look pnp4nagios
documentation. 

=over 4

=item * /software/components/pnp4nagios/npcd

Named list of npcd configuration options.

=item * /software/components/pnp4nagios/php

Named list of php configuration options.

=item * /software/components/pnp4nagios/pages : page{}

Named list of C<page> structures, indexed by C<page> file name. 

=item * /software/components/pnp4nagios/templates : template{}

Named list of C<template> structures, indexed by C<template> file name.

=back

=cut
