# ${license-info}
# ${developer-info}
# ${author-info}


=head1 NAME

NCM::mailaliases - NCM mailaliases configuration component

=head1 SYNOPSIS

=over

=item Configure()

Configures the forwards for /etc/aliases

=item Unconfigure()

not available.

=back

=head1 RESOURCES

=over

=item "/software/components/mailaliases/user/<USERNAME>/recipients" = list(email addresses);

Each user can have a list of email addresses, which will be put into the
mailaliases file. newaliases is run in case changes were made.

"/system/rootmail" should no longer be used, though it is still allowed.

=back

=head1 DEPENDENCIES

None.

=head1 BUGS

None known.

=head1 AUTHOR

Thorsten Kleinwort <Thorsten.Kleinwort@cern.ch>

=head1 SEE ALSO

ncm-ncd(1)

=cut
