# ${license-info}
# ${developer-info}
# ${author-info}


=pod

=head1 DESCRIPTION

The I<fstab> component manages the mount points in a node. It is able
to manipulate C<< /etc/fstab >>, and remount filesystems as specified by the
profile. It doesn't perform any dangerous operations, such as
formatting or partitioning. If you need so, use ncm-filesystems in
addition to this component.

It doesn't remove any filesystems specified under
C<< /software/components/fstab/protected_mounts >>.

=cut
