# ${license-info}
# ${developer-info}
# ${author-info}

=head1 NAME

NCM::etcservices - /etc/services configuration component.

=head1 DESCRIPTION

The services file is a local source of information regarding each service available through the Internet.

=head1 SYNOPSIS

=over

=item Configure()

Configure /etc/services entries

=back

=head1 RESOURCES

=over

=item * C<< /software/components/etcservices/active >> : boolean

activates/deactivates the component.

=item * C<< /software/components/etcservices/entries >>

The services file contains an entry for each service. Each entry has the form:

  service-name port/protocol aliases

=over

=item * service-name: This is the official Internet service name.

=item * port/protocol: This field is composed of the port number and protocol through which the service is provided.

=item * aliases: This is a list of alternate names by which the service might be requested.

=back

=back

=cut
