# ${license-info}
# ${developer-info}
# ${author-info}


=head1 NAME

NCM::syslog - adding entries and editing /etc/syslog.conf

=head1 RESOURCES

=over

=item * C<< /software/components/syslog/active >> : boolean

Activates/deactivates the component.

=item * C<< /software/components/syslog/fullcontrol >> : boolean

Determines whether component has full control over C<< /etc/syslog.conf >>,
eventually erasing entries from other sources, or whether entries
from other sources are kept.

=item * C<< /software/components/syslog/syslogdoptions >> : string

Options for syslogd C<< /etc/sysconfig/syslog >>

=item * C<< /software/components/syslog/syslogdoptions >> : string

Options for the klogd C<< /etc/sysconfig/syslog >>

=item * C<< /software/components/syslog/config/ >>

The configuration items.

=back

=cut
