# ${license-info}
# ${developer-info}
# ${author-info}


=head1 NAME

NCM::syslog - adding entries and editing /etc/syslog.conf

=head1 SYNOPSIS

=over

=item Configure()

=item Unconfigure()

=back

=head1 RESOURCES

=over

=item /software/components/syslog/active : boolean

activates/deactivates the component.

=item /software/components/syslog/fullcontrol : boolean

determines whether component has full control over /etc/syslog.conf, eventually erasing
entries from other sources, or whether entries from other sources are kept

=item /software/components/syslog/syslogdoptions : string

Options for syslogd (/etc/sysconfig/syslog)

=item /software/components/syslog/syslogdoptions : string

Options for the klogd (/etc/sysconfig/syslog)

=item /software/components/syslog/config/

The configuration items 

=back

=head1 DEPENDENCIES

=head2 Components to be run before:

none.

=head2 Components to be run after:

none.

=head1 BUGS

none known.

=head1 AUTHOR

Ulrich Schwickerath <ulrich.schwickerath@cern.ch>

=head1 SEE ALSO

ncm-ncd(1), sysklogd(8)

=cut
