# ${license-info}
# ${developer-info}
# ${author-info}


=head1 NAME

NCM::ntpd - NCM ntpd configuration component

=head1 SYNOPSIS

=over

=item Configure()

This component configures the ntpd (Network Time Protocol) server to
start at boot time, and configures the time servers from CDB. If
anything changed in the configuration, it will restart ntpd.

=item Unconfigure()
Does nothing.

=back

=head1 RESOURCES

=over

=item /software/components/ntpd/active : boolean

activates/deactivates the component.

=item /software/components/ntpd/servers/ : list of time servers

=item /software/components/ntpd/clientnetworks : list of { net=, mask= }

optional: clients that can use this server to synchronize. Default allows
connections from localhost only.

=back

=head1 DEPENDENCIES

=head2 Components to be run before:

none.

=head2 Components to be run after:

none.

=head1 BUGS

none known.

=head1 AUTHOR

Thorsten Kleinwort <Thorsten.Kleinwort@cern.ch>

=head1 SEE ALSO

ncm-ncd(1), ntpd(1)

=cut
