# ${license-info}
# ${developer-info}
# ${author-info}


=head1 NAME

sshkeys: NCM component to manage ssh key files.

=head1 DESCRIPTION

The I<sshkeys> component manages the ssh key files as well as the
known hosts file.

IMPORTANT NOTE: Using this component requires that private keys be in
the pan templates and the generated low-level description (LLD) file
transported to the client.  DO NOT USE THIS COMPONENT UNLESS:

=over

=item *

The profiles on the quattor server are protected via SSL (and
the configuration requires client authentication).

=item *

The CCM component fetching the profile produces a cache with
proper permissions (usually owned and readable ONLY by root).

=item The templates in the CDB are readable only by authorized
people.

=back

If these conditions are not met, you will seriously compromise your
machines by making private key information generally available.

=head1 RESOURCES

=head2 /software/components/sshkeys/{rsa1|rsa|dsa}/{public|private}

The public and private key pair for each protocol: RSA1 (SSH1), RSA
(SSH2), and DSA.  All of these keys are required.

=head2 /software/components/sshkeys/knownhosts

List of entries containing information for the SSH known hosts file.
Each entry contains a list of hostnames ("hostnames") and the
associated PUBLIC key ("key").  A list of hostnames is used to allow
aliases and the raw IP to be specified for each host.

=cut
