# ${license-info}
# ${developer-info}
# ${author-info}

=head1 DESCRIPTION

The I<openvpn> component manages the OpenVPN server and the OpenVPN client configuration.
OpenVPN is used to make virtual private networks over the internet.

=head1 COMPONENT STRUCTURE

This component can be used to configure an OpenVPN and/or OpenVPN
client.

The server is only configured if its configuration exists under
C<< /software/components/openvpn/server >>, the client parts are configured if
the configuration under C<< /software/components/openvpn/clients >> is defined.
It is possible to generate multiple configurations of the client and
server type. When setting one of the boolean options to C<< True >> you'll
activate the option in the configuration.

=cut
