# ${license-info}
# ${developer-info}
# ${author-info}


=head1 NAME

NCM::pakiti - NCM pakiti client configuration component

=head1 SYNOPSIS

=over

=item Configure()

Configures the pakiti client (/etc/pakiti/pakiti-client.conf).

=item Unconfigure()

not available.

=back

=head1 RESOURCES

=over

=item "/software/components/pakiti/server_url" = server_url;

The pakiti server URL (i.e. https://monitor.grid.auth.gr/services/yumit/GR-01-AUTH/feed/)

=item "/software/components/pakiti/admin" = admin;

The pakiti admin (i.e. GR-01-AUTH Admin)

=back

=head1 DEPENDENCIES

None.

=head1 BUGS

None known.

=head1 AUTHOR

Christos Triantafyllidis <ctria@grid.auth.gr>

=head1 SEE ALSO

ncm-ncd(1)

=cut

