# -*- mode: cperl -*-
# ${license-info}
# ${author-info}
# ${build-info}

=pod

=head1 DESCRIPTION

Tests for the DNF module management methods in NCM::Component::spma::dnf:
C<generate_dnf_modules> and C<set_default_modules>.

=head1 TESTS

=cut

use strict;
use warnings;
use Test::More;
use Test::Quattor qw(dnf_modules);
use NCM::Component::spma::dnf;
use CAF::Object;
use Test::Quattor::Object;
use Readonly;
use File::Path qw(mkpath rmtree);

use Test::Quattor::TextRender::Base;

my $caf_trd = mock_textrender();

$CAF::Object::NoAction = 1;

my $obj = Test::Quattor::Object->new;

my $cmp = NCM::Component::spma::dnf->new("spma", $obj);

Readonly my $MODULES_DIR => "target/test/dnf.modules.defaults.d";

sub initialize_modules_dir {
    rmtree($MODULES_DIR) if -d $MODULES_DIR;
    mkpath($MODULES_DIR);
}

sub create_module_file {
    my ($name) = @_;
    open(my $fh, ">", "$MODULES_DIR/$name.yaml");
    close($fh) or die("Could not write $name.yaml: $!"); 
}

=pod

=head2 Test generate_dnf_modules

=cut

initialize_modules_dir();

my $modules = {
    'postgresql' => { stream => '13' },
    'nodejs' => { stream => '16' },
};

my $changes = $cmp->generate_dnf_modules($MODULES_DIR, $modules);
ok(defined($changes), "generate_dnf_modules returns defined value");

my $head = "# File generated by NCM::Component::spma::dnf. Do not edit\n";

my $fh = get_file("$MODULES_DIR/postgresql.yaml");
ok(defined($fh), "postgresql module file created");
like("$fh", qr/postgresql/, "postgresql module file has correct content");

$fh = get_file("$MODULES_DIR/nodejs.yaml");
ok(defined($fh), "nodejs module file created");
like("$fh", qr/nodejs/, "nodejs module file has correct content");

=pod

=head2 Test set_default_modules with config

=cut

initialize_modules_dir();
create_module_file("wanted_mod");
create_module_file("unwanted_mod");

my $cfg = get_config_for_profile("dnf_modules");

# Track cleanup calls
my @cleaned_files;
my $mock_cmp = Test::MockModule->new('NCM::Component::spma::dnf');
$mock_cmp->mock('cleanup', sub {
    my ($self, $file) = @_;
    push @cleaned_files, $file;
    unlink $file or warn("Failed to remove $file: $!");
    return 1;
});

my $result = $cmp->set_default_modules($cfg, $MODULES_DIR);
ok($result, "set_default_modules returns success");

ok(!-e "$MODULES_DIR/unwanted_mod.yaml", "Unwanted module file removed");

=pod

=head2 Test set_default_modules with missing directory

=cut

rmtree($MODULES_DIR) || warn("Failed to cleanup $MODULES_DIR: $!");

$result = $cmp->set_default_modules($cfg, $MODULES_DIR);
ok($result, "set_default_modules handles missing directory");

=pod

=head2 Cleanup

=cut

rmtree($MODULES_DIR) if -d $MODULES_DIR;

done_testing();
