# ${license-info}
# ${developer-info}
# ${author-info}


Creates a new /etc/krb5.keytab and /etc/srvtab or overwrites an
existing one. Uses the CERN-specific C<cern-config-keytab> or
C<cern-config-srvtab> tools (that internally use C<arc>).

=item Unconfigure()

Does nothing, the old files are left in place (since they don't hurt).

=head1 RESOURCES

=item /software/components/srvtab/active : boolean

activates/deactivates the component.

=item /software/components/srvtab/server : string

the KDC to talk to (needs to be running the arc server).

=item /software/components/srvtab/overwrite : bool

junk existing /etc/srvtab and/or /etc/krb5.keytab.

=item /software/components/srvtab/verbose : bool

tell the script generating the keytab to be more verbose - may leak
sensitive information into log files.

=head1 DEPENDENCIES

=head2 Components to be run before:

none.

=head2 Components to be run after:

none.

=head1 AUTHOR

Jaroslaw Polok <jaroslaw.polok@cern.ch>

=head1 SEE ALSO

arc(1)

=cut

1; #required for Perl modules


### Local Variables: ///
### mode: perl ///
### End: ///
