# ${license-info}
# ${developer-info}
# ${author-info}


=head1 NAME

pvss: NCM component to configure and patch a PVSS installation

=head1 DESCRIPTION

the I<pvss> component does the following :
 - install the licence file.
     If no licence is found on the server, send a mail with all need informations
 - apply PVSS patches
 - removes the sticky bit on the /tmp folder
 - makes the pvss log folder world writable
 - adds checkMemory = 0 to the config file
 - configures the projects to be started at system startup by the pvss_mp init script

=head1 RESOURCES

=head2 /software/components/pvss/rooturl : string

define the base url where the licence files and the patches will be found
(2 subfolders : licences & patches)

=head2 /software/components/pvss/pvsspath : string

define where is installed pvss

=head2 /software/components/pvss/licencefilename : string

defines the filename of the licence on the server

=head2 /software/components/pvss/patches : pvss_patch_type list

List of patches to apply

=head3 /software/components/pvss/patches/XX/patchfilename : string

filename of the patch

=head3 /software/components/pvss/patches/XX/patchpresencefilename : string

name of the file that will be created in the pvss folder to show the patch presence

=head2 /software/components/pvss/datacheckmemoryhack : boolean

add checkMemory = 0 to the config file if true

=head2 /software/components/pvss/stickybithack : boolean

removes the sticky bit on the /tmp folder if true

=head2 /software/components/pvss/logfolderhack : boolean

makes the pvss log folder world writable if true

=head2 /software/components/pvss/projects : pvss_project_type list

list of projects to start at boot time

=head3 /software/components/pvss/projects/XX/projectname : string

name of the project : will simply be the name of the config file in /etc/pvss.d/

=head3 /software/components/pvss/projects/XX/projectpath : string

path to the project config file

=head3 /software/components/pvss/projects/XX/projectuser ? string

if defined, the project will be started as this user

=head2 /software/components/pvss/mail_address : string

where to send Licences inquiries

=cut
