# ${license-info}
# ${developer-info}
# ${author-info}

=head1 NAME

mcx : MCX NCM component.

=head1 DESCRIPTION

Generic MCX component. This component does not do any filtering of MCX values, but directly applies provided configuration into the local MCX configuration of the OS X computer. 

=head1 RESOURCES

=head2 C<< /software/components/mcx/configuration >>

An nlist of MCX data to apply.

=cut
