#!/usr/bin/perl
# -*- mode: cperl -*-
use strict;
use warnings;
use Test::More;
use Test::Quattor;
use NCM::Component::metaconfig;
use CAF::Object;

eval {use Config::Properties};
plan skip_all => "Config::Properties not found" if $@;

$CAF::Object::NoAction = 1;

=pod

=head1 DESCRIPTION

Test that a JSON config file can be generated by this component.

=cut


my $cmp = NCM::Component::metaconfig->new('metaconfig');

my $cfg = {
    foo => {
        bar => [0..2]
       }
};

like($cmp->properties($cfg), qr{foo.bar\.0=0\nfoo.bar.1=1\nfoo.bar.2=2$},
     "Properties work correctly");

done_testing();
