use strict;
use warnings;
use Test::More;
use Test::Quattor;
use NCM::Component::metaconfig;
use CAF::Object;

use Config::Properties;

=pod

=head1 DESCRIPTION

Test that a Java properties file can be generated by this component.

=cut


my $cmp = NCM::Component::metaconfig->new('metaconfig');

my $cfg = {
       owner => 'root',
       group => 'root',
       mode => 0644,
       contents => {
            foo => {
                bar => [0..2]
                }
            },
       module => "properties",
      };

$cmp->handle_service("/foo/bar", $cfg);

my $fh = get_file("/foo/bar");
isa_ok($fh, "CAF::FileWriter", "Correct class");

like("$fh", qr{foo.bar\.0=0\nfoo.bar.1=1\nfoo.bar.2=2\n\n$},
     "Properties work correctly");

done_testing();
