#!/usr/bin/perl
# -*- mode: cperl -*-
use strict;
use warnings;
use Test::More;
use Test::Quattor;
use NCM::Component::metaconfig;
use CAF::Object;
use Readonly;

eval {use Config::Tiny;};

Readonly my $STR => "An arbitrary string";

plan skip_all => "Config::Tiny not found" if $@;

$CAF::Object::NoAction = 1;

our $sane_templates = "foo/bar";


=pod

=head1 DESCRIPTION

Test that a config file can be generated by this component, using
Config::Tiny to render simple configuration files.

The expected format is either

    key=value

or

    [section]
    key=value

Where sections are nlists in the component's schema.

=head1 TESTS

=cut


my $cmp = NCM::Component::metaconfig->new('metaconfig');

my $cfg = {
    'a' => 1,
    'b' => 2
   };

my $restart = 1;

=pod

=head2 Simple method execution.

We expect just C<key=value> lines

=cut

is($cmp->tiny($cfg), "a=1\nb=2\n",
   "Method returns the expected string");

=pod

=head2 Files with sections

They should appear when there are nlists (hashes) inside the
structure.

=cut

$cfg = { section => { a => 1 } };

is($cmp->tiny($cfg), "[section]\na=1\n",
   "Sections in the file are rendered properly");

done_testing();
