#!/usr/bin/perl
# -*- mode: cperl -*-
use strict;
use warnings;
use Test::More;
use Test::Quattor;
use NCM::Component::metaconfig;
use CAF::Object;

eval {use Template};

use Readonly;

Readonly my $STR => "An arbitrary string";

plan skip_all => "Template::Toolkit not found" if $@;

$CAF::Object::NoAction = 1;

no warnings 'redefine';
*NCM::Component::template = sub {
    my ($self) = @_;
    return $self;
};

sub NCM::Component::process {
    my ($self, $file, $cfg, $str) = @_;
    $self->{$file}->{CFG} = $cfg;
    $self->{$file};

    $$str = $STR;
    return !$self->{$file}->{failed};
}

use warnings 'redefine';

=pod

=head1 DESCRIPTION

Test that a config file can be generated by this component, using
Template::Toolkit to render an arbitrary file format.

=cut


my $cmp = NCM::Component::metaconfig->new('metaconfig');

my $cfg = {
	   owner => 'root',
	   group => 'root',
	   mode => 0644,
	   contents => {
			foo => 1,
			bar => 2,
			baz => {
				a => [0..3]
				}
			},
	   daemon => 'httpd',
	   module => "tt",
	  };

my $restart = 1;

no warnings 'redefine';
*NCM::Component::metaconfig::needs_restarting = sub {
    return $restart;
};
use warnings 'redefine';

is($cmp->tt($cfg->{contents}, "/foo/bar/baz.conf"), $STR,
   "Method returns the expected string");
my $tpl_call = $cmp->{"metaconfig/bar/baz.tt"};
ok($tpl_call, "Correct template name generated");
is($tpl_call->{CFG}, $cfg->{contents},
   "Template processed with the correct configuration");
ok(!exists($cmp->{ERROR}), "No errors in this run");

$tpl_call->{failed} = 1;
$cmp->tt($cfg->{contents}, "/foo/bar/baz.conf");
is($cmp->{ERROR}, 2, "Errors reported when the template processing fails");

done_testing();
