# ${license-info}
# ${developer-info}
# ${author-info}


=head1 NAME

NCM::linuxha - NCM Linux-HA configuration component

=head1 SYNOPSIS

=over

=item Configure()

Creates (overwrites!) the following files based on CDB information:

F</etc/ha.d/ha.cf>

F</etc/ha.d/haresources>

F</etc/ha.d/authkeys>

Method also tells Linux-HA daemon (heartbeat) to reload the new configuration
by calling this command:

service heartbeat reload

=item Unconfigure()

Does nothing.

=back

=head1 RESOURCES

=over

=item /software/components/linuxha/active : boolean

activates/deactivates the component.

=back

=head1 DEPENDENCIES

None.

=head1 BUGS

None known.

=head1 AUTHOR

Andras Horvath <Andras.Horvath@cern.ch>

=head1 SEE ALSO

ncm-ncd(1), /usr/share/doc/heartbeat/

=cut
