# ${license-info}
# ${developer-info}
# ${author-info}

=pod

=head1 DESCRIPTION

The I<aiiserver> component manages the configuration of an AII
(Automated Installation Infrastructure) server.

=head1 STRUCTURE

The following fields are provided:

=over 4

=item * C<< /software/components/aiiserver/aii-shellfe >>

Configures the aii-shellfe tool. See the schema for more information.

=item * C<< /software/components/aiiserver/aii-dhcp >>

Configures the aii-dhcp legacy tool. See the schema for more information.

This components also uses configuration parameters related to https from L<ncm-ccm>: ca_dir, ca_file, cert_file, key_file.

=back

=cut
