# ${license-info}
# ${developer-info}
# ${author-info}

=head1 NAME

NCM::fmonagent - NCM Lemon Monitoring Agent configuration component

=head1 SYNOPSIS

=over

=item Configure()

Creates configuration file(s) and restarts the lemon-agent service.
In case of the single file configuration the files
is defined in the CDB template as file and in case of split file as 
a directory where the following structure is expected:

	top_dir/general.conf
	top_dir/transport/
	top_dir/metrics/
	top_dir/sensors/

Component will try in this case to modify the C<< top_dir/general.conf >>,
C<< top_dir/transport/udp.conf >>, C<< top_dir/metrics/default.conf >> and
for each sensor C<< top_dir/sensors/sensor_name.conf >> files.

=back

=head1 RESOURCES

=over

=item C<< /software/components/fmonagent/active >> : boolean

Activates/deactivates the component.

=back

=head2 Warning

This version of NCM::fmonagent will not work with sensorAlarm!

=head2 Required programs.

Requires lemon-agent rpm to be installed.

=cut
