# ${license-info}
# ${developer-info}
# ${author-info}


=head1 NAME

NCM::chkconfig - NCM chkconfig component

=head1 SYNOPSIS

=item Configure()

Updates runlevel information for system services by using B<chkconfig> that are
defined in /software/components/chkconfig/. 

Also starts/stops those services that have option C<startstop> set to true in 
and have one of the following options specified: 
C<add> or C<del> option is true, C<on> or C<off> option is specified either 
without specific runlevels, or with runlevel value that contains the current runlevel. 

The optional I<default> key decides what will happen with services that are not explicitly
configured. Default is to ignore them, but a vakue of I<off> instead disables anything
not mentioned in the profile.

=item Unconfigure()

Not available.


=head1 RESOURCES

=item /software/components/chkconfig/active : boolean

activates/deactivates the component.

=item /software/components/chkconfig/default : string ("off", "ignore")

says what happens if no other configuration is found for the service.

=item /software/components/chkconfig/service/<service>/off : string ("[0-7]*")

=item /software/components/chkconfig/service/<service>/on : string ("[0-7]*")

Sets the service <service> on/off on specified run levels. The run levels are
specified as string of numbers, the same way as with chkconfig-command. If the
string is empty, system default is taken (see man chkconfig(8) for exact details).

=item /software/components/chkconfig/service/<service>/name : string 

If set, the value is used as the name of the service instead of using the 
<service> path as a name. 

=item /software/components/chkconfig/service/<service>/reset : string ("[0-7]*")
Resets the service on defined run levels. Reset with no run levels specified 
affects every run level. 


=item /software/components/chkconfig/service/<service>/add : boolean

If the value is true, adds service for management by chkconfig, otherwise the
option is ignored. 


=item /software/components/chkconfig/service/<service>/del : boolean

If the value is true, removes service from management by chkconfig, otherwise
the option is ignored. 


=item /software/components/chkconfig/service/<service>/startstop : boolean

If true, the service is also started/stopped when the service is added,
removed or turned off/on.

=head1 DEPENDENCIES

None.

=head1 BUGS

None known.

=head1 AUTHOR

Teemu Sidoroff <Teemu.Sidoroff@cern.ch>

=head1 SEE ALSO

ncm-ncd(1), chkconfig(8), http://cern.ch/quattor

=cut
